image: jamesdesq/node_ng:master

pipelines:
  default:
    - step:
        script: 
          - npm install
          - npm install -g @angular/cli
          - ng build contentful-connector
          - ng build --prod
          - cd dist/scowsite
          - aws s3 ls s3://henryscowcroft.net
          - aws s3 sync . s3://henryscowcroft.net
          - git remote add sync git@github.com:jamesdesq/new-serverless-cms.git
          - git checkout -b feature/publish-to-github
          - cd ../..
          - rm -rf ./src/environments
          - rm -rf ./dist
          - git status
          - git add . 
          - git commit -m "Syncing to Github" 
          - git push sync feature/publish-to-github:master