image: jamesdesq/node_ng:master

pipelines:
  default:
    - step:
        script: 
          # - node -v
          - npm install
          - npm install -g @angular/cli
          - ng build -–prod
          - cd dist/scowsite
          - aws s3 ls s3://henryscowcroft.net
          - aws s3 sync . s3://henryscowcroft.net